email_categorization:
  default:
    provider: "zhipuai"
    model: "glm-4-flash"
    temperature: 0.1
    api_key_env: "ZHIPUAI_API_KEY"
  fast:
    provider: "openai"
    model: "gpt-3.5-turbo"
    temperature: 0.1
    api_key_env: "OPENAI_API_KEY"

rag_query_generation:
  default:
    provider: "zhipuai"
    model: "glm-4-flash"
    temperature: 0.1
    api_key_env: "ZHIPUAI_API_KEY"
  creative:
    provider: "anthropic"
    model: "claude-3-haiku-20240307"
    temperature: 0.3
    api_key_env: "ANTHROPIC_API_KEY"

email_writing:
  default:
    provider: "zhipuai"
    model: "glm-4-flash"
    temperature: 0.3
    api_key_env: "ZHIPUAI_API_KEY"
  creative:
    provider: "anthropic"
    model: "claude-3-sonnet-20240229"
    temperature: 0.7
    api_key_env: "ANTHROPIC_API_KEY"
  fast:
    provider: "openai"
    model: "gpt-3.5-turbo"
    temperature: 0.5
    api_key_env: "OPENAI_API_KEY"

email_proofreading:
  default:
    provider: "zhipuai"
    model: "glm-4-flash"
    temperature: 0.1
    api_key_env: "ZHIPUAI_API_KEY"
  precise:
    provider: "openai"
    model: "gpt-4"
    temperature: 0.1
    api_key_env: "OPENAI_API_KEY"

# Embedding configurations for RAG
embeddings:
  default:
    provider: "zhipuai"
    model: "embedding-3"
    api_key_env: "ZHIPUAI_API_KEY"
  openai:
    provider: "openai"
    model: "text-embedding-3-small"
    api_key_env: "OPENAI_API_KEY"
  openai_large:
    provider: "openai"  
    model: "text-embedding-3-large"
    api_key_env: "OPENAI_API_KEY"
  openrouter:
    provider: "openrouter"
    model: "openai/text-embedding-3-small"
    api_key_env: "OPENROUTER_API_KEY"

# Default embedding mappings for each provider
# When a LLM model is specified, these embeddings will be used
default_embeddings:
  zhipuai: "embedding-3"
  openai: "text-embedding-3-small"
  anthropic: "text-embedding-3-small"  # Use OpenAI embedding for Anthropic LLMs
  openrouter: "text-embedding-ada-002"  # Use OpenRouter supported embedding model